---

- hosts: cluster-all
  gather_facts: false
  environment: "{{proxy_env|d({})}}"
  strategy: free
  tasks:
    # 1. Install required packages to run ansible on hosts
    - import_role:
        name: bootstrap-os
      vars:
        ansible_ssh_pipelining: false
      tags:
        - prepare-hosts
        - init-hosts

- hosts: container-hosts
  environment: "{{proxy_env|d({})}}"
  strategy: mitogen_free
  tasks:
    - import_role:
        name: container-engine
      vars:
        ansible_ssh_pipelining: true
      tags:
        - container-engine
        - init-hosts
